### ISSUE TITLE
Hi, great control. Possible to add support for iOS 5 + ARC?

### ISSUE THREAD

**Issue by ipeisong** [ikhsan/IAInfiniteGridView#2]
Would love to see that if possible :)

**Comment by ikhsan** [comment]
The current code doesn't use any iOS 6 specific API, so it supports iOS 5 and supports ARC from the first place. The sample code can't be build to iOS 5 because it uses auto layout. I've downgraded the views to use spring & struts. You can change the deployment target to 5.0, set the build settings to iOS 5.0 and you're good to go.
